// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG_0s09O1_81SGJVWKi50EV3DZBzBWW9s',
    appId: '1:43248958853:web:ee71ea48931d080e3718ec',
    messagingSenderId: '43248958853',
    projectId: 'minimalchatapp-5fd78',
    authDomain: 'minimalchatapp-5fd78.firebaseapp.com',
    storageBucket: 'minimalchatapp-5fd78.appspot.com',
    measurementId: 'G-MQG454ZK5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChZXsSa0eY06sjXrf5zdb7lUM3ftBftx8',
    appId: '1:43248958853:android:35e8a317503e8b9a3718ec',
    messagingSenderId: '43248958853',
    projectId: 'minimalchatapp-5fd78',
    storageBucket: 'minimalchatapp-5fd78.appspot.com',
  );
}
